[tool.black]
target-version = ["py38"]
line-length = 88
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
combine_as_imports = true
multi_line_output = 3

[tool.pylint.master]
py-version = "3.8"
ignore = []
jobs = 2
suggestion-mode = "yes"

[tool.pylint.basic]
argument-naming-style = "any"
variable-naming-style = "any"

[tool.pylint.format]
expected-line-ending-format = "LF"
max-line-length = 120

[tool.pylint.design]
min-public-methods = 0

[tool.pylint.message_control]
disable = [
    "broad-except",
    "consider-using-with",
    "import-outside-toplevel",
    "missing-docstring",
    "pointless-string-statement",
]

[tool.mypy]
python_version = 3.8
exclude = ["build|dist|venv"]
ignore_missing_imports = true
show_error_codes = true

[[tool.mypy.overrides]]
module = []
ignore_errors = true
